steps:
  - name: 'hashicorp/terraform:full'
    args: [ 'init']
    dir: 'god'
  - name: 'hashicorp/terraform:full'
    args: [ 'plan', '.']
    dir: 'god'
  - name: 'hashicorp/terraform:full'
    args: [ 'apply', '-auto-approve', '.']
    dir: 'god'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'builds', 'submit', '--project', 'tftest-20181128f', '--config', 'tftest-20181128f/cloudbuild.yaml']